# Generated by Django 3.1 on 2020-08-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('world', '0005_homebase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeBase',
            new_name='Base',
        ),
    ]
